name: example-environment
channels:
  - conda-forge
dependencies:
  - tqdm
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - requests
  - pip:
    - azure-kusto-data
    - azure-kusto-ingest
